### ISSUE TITLE
Horizon timeout issues

### ISSUE THREAD

**Issue by logix-bfarrington** [rconfig/rconfig#55]
I am unable to pull a full configuration from our Nokia 7750 SR devices. These devices have heavy traffic and quite large configurations. Running the debug CLI command works fine, however it does take upwards of 15 minutes to complete. Running the task through Horizon, the result is always the same - the job fails with a timeout claiming it made 5 attempts in 120s despite it making only one attempt and taking far longer. Packet captures show the configuration is being retrieved but is cut off mid output. I have attempted to adjust the timeout setting in the connection template - although I don't believe this to be the issue since the CLI command runs, and HORIZON_PROD_TIMEOUT in .env - followed by `php artisan rconfig:clear-all` to apply the changes. Neither adjustment seems to have made any impact on the outcome through Horizon. We have several of these devices, all of which are having this issue. How can we effectively increase the timeout to allow these to run through Horizon?

OS VERSION
Ubuntu 22.04.3 LTS
SERVERNAME
dal-rconfig-1
LOCAL IP
127.0.1.1
PUBLIC IP
66.64.39.210
PHP / LARAVEL VERSION
8.2.9 / 10.12.0
REDIS VERSION
6.0.16
MYSQL VERSION
10.6.12

### debug CLI command

> $ time (cd /var/www/html/rconfig && php artisan rconfig:download-device 33 -d)
> ...
> Start device download for NOKIA7750-1 ID:33
> Config downloaded for NOKIA7750-1 with command: "admin display-config detail" was successful
> End rconfig:download-device
> 
> real    16m4.792s
> user    15m45.741s
> sys     0m4.693s

### Log output

> [2023-08-21 15:58:08] production.ERROR: Job failed: App\Jobs\DownloadConfigNow(App\Jobs\DownloadConfigNow has timed out.)
> [2023-08-21 15:58:09] production.ERROR: Job failed: App\Jobs\DownloadConfigNow(App\Jobs\DownloadConfigNow has been attempted too many times.)
> [2023-08-21 15:58:09] production.ERROR: App\Jobs\DownloadConfigNow has been attempted too many times. {"exception":"[object] (Illuminate\\Queue\\MaxAttemptsExceededException(code: 0): App\\Jobs\\DownloadConfigNow has been attempted too many times. at /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:785)
> [stacktrace]
> #0 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(519): Illuminate\\Queue\\Worker->maxAttemptsExceededException()
> #1 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\\Queue\\Worker->markJobAsFailedIfAlreadyExceedsMaxAttempts()
> #2 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\\Queue\\Worker->process()
> #3 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\\Queue\\Worker->runJob()
> #4 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(136): Illuminate\\Queue\\Worker->daemon()
> #5 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(119): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
> #6 /var/www/html/rconfig/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\\Queue\\Console\\WorkCommand->handle()
> #7 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
> #8 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
> #9 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
> #10 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
> #11 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
> #12 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\\Container\\Container->call()
> #13 /var/www/html/rconfig/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
> #14 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Console/Command.php(177): Symfony\\Component\\Console\\Command\\Command->run()
> #15 /var/www/html/rconfig/vendor/symfony/console/Application.php(1040): Illuminate\\Console\\Command->run()
> #16 /var/www/html/rconfig/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
> #17 /var/www/html/rconfig/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
> #18 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(200): Symfony\\Component\\Console\\Application->run()
> #19 /var/www/html/rconfig/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
> #20 {main}
> "}

**Comment by stephenstack** [comment]
When you run the manual cli debug, do you get the full config (even after the 15 mins)?

When you update the HORIZON_PROD_TIMEOUT value in the ENV file….  And after running the clear command. You could validate that the new timeout was cached in the app correctly. 
```bash
cd /var/www/html/rconfig
php artisan tinker
Config::get('horizon.environments.production');
```

What was the timeout set to?

The other thing, I’d try is to output the debug to a text file, and review it after. If it takes 15 minutes, each transactions time (assuming SSH), is recorded in the debug. This may pinpoint areas for improvement.

**Comment by logix-bfarrington** [comment]
Thanks for the reply.
Yes, we do get the full configuration and it shows up in the frontend when running the manual cli debug command.

The changes to .env do appear to be altering the timeout setting:

> $ php artisan tinker
> Psy Shell v0.11.20 (PHP 8.3.0beta3 — cli) by Justin Hileman
> > Config::get('horizon.environments.production');
> = [
>     "supervisor-1" => [
>       "connection" => "redis",
>       "queue" => [
>         "default",
>         "downloadqueue",
>         "lastqueue",
>       ],
>       "balance" => "auto",
>       "processes" => 10,
>       "tries" => 1,
>       "timeout" => 3600,
>     ],
>   ]
> 
> >
> 

Despite this, the job still times out well before the configured timeout.

**Comment by logix-bfarrington** [comment]
I took a bit of a dive into the code and found the issue. There appears to be a hard-coded limit of 120s in DownloadConfigNow.php. Changing this allows the job to complete successfully.

```
--- DownloadConfigNow.php.orig  2023-08-22 13:47:50.452852064 -0500
+++ DownloadConfigNow.php       2023-08-22 13:26:35.520917816 -0500
@@ -18,7 +18,7 @@
 
      public $tries = 5;
 
 -    public $timeout = 120;
 +    public $timeout = 3600;
 
      protected $username;
```

**Comment by stephenstack** [comment]
Hi, Is this still working for you? The timeout you reference above is actually orphaned code. So i'm surprised it made a difference.

**Comment by stephenstack** [comment]
Closing due to no response.

**Comment by YellowJacket51** [comment]
Hey @stephenstack I have the same issue with Cisco config backups. ended up having to go into the DownloadConfigNow.php and increase the public timeout.

**Comment by stephenstack** [comment]
@YellowJacket51 so when you increased public timeout in DownloadConfigNow the longer download worked? I'll review this and get an update out this week.

**Comment by stephenstack** [comment]
@YellowJacket51 so when you increased publci timeout in DownloadConfigNow the longer download worked? I'll review this and get an update out this week.

**Comment by stephenstack** [comment]
Closing due to inactivity

**Comment by YellowJacket51** [comment]
Sorry for the late response. Yes, I increased the public timeout and this resolve the issue.
